### ISSUE TITLE
Fail in scripts/project_wizard.py

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#354]
With python3 version 3.7.4 on macOS Catalina, project_wizard.py fails with
```
$ ../Ada_Drivers_Library/scripts/project_wizard.py
[...]
? Traceback (most recent call last):
  File "../Ada_Drivers_Library/scripts/project_wizard.py", line 377, in <module>
    args.object_dir)
  File "../Ada_Drivers_Library/scripts/project_wizard.py", line 170, in ADL_configuration
    board_config(config)
  File "../Ada_Drivers_Library/scripts/project_wizard.py", line 28, in board_config
    config.query_enum_key("Board", list_of_boards(), "Custom_Board")
  File "/Users/simon/adacore/Ada_Drivers_Library/scripts/config/__init__.py", line 202, in query_enum_key
    default=default)
  File "/Users/simon/adacore/Ada_Drivers_Library/scripts/config/__init__.py", line 165, in query_key
    self.ask_the_user(key, validation, default)
  File "/Users/simon/adacore/Ada_Drivers_Library/scripts/config/__init__.py", line 130, in ask_the_user
    default)
  File "/Users/simon/adacore/Ada_Drivers_Library/scripts/config/user_input/console.py", line 71, in query_choice
    choice = raw_input()
NameError: name 'raw_input' is not defined
```

If I run `$ python2 ../Ada_Drivers_Library/scripts/project_wizard.py` it works correctly.

**Comment by Fabien-Chouteau** [comment]
Thanks for the report @simonjwright.

I have a fix in review: #355.
